### ISSUE TITLE
Unable to resolve module `react-native-svg` from `node_modules\react-native-eva-icons\icons\Activity.js`: react-native-svg could not be found within the project

### ISSUE THREAD

**Issue by ThukuWakogi** [artyorsh/react-native-eva-icons#30]
## 🐛 Bug Report

I'm trying to use `react-native-eva-icons` but this error pops up making the app crash

```
error: Error: Unable to resolve module `react-native-svg` from `node_modules\react-native-eva-icons\icons\Activity.js`: react-native-svg could not be found within the project.

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules: rm -rf node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
    at ModuleResolver.resolveDependency (D:\olive\Documents\Developer\phone\MPF-front-native\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:186:15)
    at ResolutionRequest.resolveDependency (D:\olive\Documents\Developer\phone\MPF-front-native\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (D:\olive\Documents\Developer\phone\MPF-front-native\node_modules\metro\src\node-haste\DependencyGraph.js:287:16)
    at Object.resolve (D:\olive\Documents\Developer\phone\MPF-front-native\node_modules\metro\src\lib\transformHelpers.js:267:42)
    at D:\olive\Documents\Developer\phone\MPF-front-native\node_modules\metro\src\DeltaBundler\traverseDependencies.js:434:31
    at Array.map (<anonymous>)
    at resolveDependencies (D:\olive\Documents\Developer\phone\MPF-front-native\node_modules\metro\src\DeltaBundler\traverseDependencies.js:431:18)
    at D:\olive\Documents\Developer\phone\MPF-front-native\node_modules\metro\src\DeltaBundler\traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (D:\olive\Documents\Developer\phone\MPF-front-native\node_modules\metro\src\DeltaBundler\traverseDependencies.js:87:24)
```

## To Reproduce

install react-native-eva-icons `yarn add react-native-eva-icons`
import Icon from react-native-eva-icons `import { Icon } from 'react-native-eva-icons'`
add icon component `<Icon name="map-outline" width={24}/>`

## Expected behavior

I expect the eva map-outline icon to be displayed

## React Native Eva Icons Version
`^1.3.1`

## Environment information
```
  System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
  Binaries:
    Node: 14.5.0 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.5 - D:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.1
      System Images: android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs 
Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom     
  npmPackages:
    react: 16.13.1 => 16.13.1
    react-native: 0.63.0 => 0.63.0
```

**Comment by artyorsh** [comment]
Do you have `react-native-svg` installed? Please check the [guide](https://github.com/react-native-community/react-native-svg#installation).
And thanks for posting. I'll update this process in the readme.
