### ISSUE TITLE
Can't find variable: Icon

### ISSUE THREAD

**Issue by gxanshu** [artyorsh/react-native-eva-icons#41]
## 🐛 Bug Report

```
[Unhandled promise rejection: ReferenceError: Can't find variable: Icon]
at node_modules/react-native-eva-icons/icons/VolumeMuteOutline.js:13:46 in exports._default
at [native code]:null in performSyncWorkOnRoot
at [native code]:null in dispatchAction
at App.js:50:19 in firebase.auth.onAuthStateChanged$argument_0
at node_modules/@firebase/auth/dist/auth.esm.js:372:584 in En
at [native code]:null in flushedQueue
at [native code]:null in callFunctionReturnFlushedQueue
```

**Comment by fachryansyah** [comment]
it's missing import package, add this
```import { Icon } from 'react-native-eva-icons';```
